# Generated by Django 3.0.3 on 2020-06-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCode',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='标题')),
                ('code', models.TextField(verbose_name='代码')),
                ('status', models.CharField(default='未完成', max_length=20, verbose_name='题目状态')),
            ],
            options={
                'verbose_name': '题目信息',
                'verbose_name_plural': '题目信息',
            },
        ),
    ]
