# Generated by Django 3.0.3 on 2020-06-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcode',
            name='remark',
            field=models.CharField(default='暂无', max_length=200, verbose_name='备注'),
        ),
    ]
