# Generated by Django 3.0.3 on 2020-06-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0002_testcode_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcode',
            name='remark',
            field=models.CharField(default='暂无说明', max_length=200, verbose_name='备注'),
        ),
    ]
